# Generated by Django 3.1 on 2020-08-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=200, unique=True)),
                ('usr_password', models.CharField(max_length=200)),
                ('usr_email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=40)),
                ('post_text', models.TextField()),
                ('post_date', models.DateTimeField()),
                ('is_public', models.BooleanField(default=False)),
                ('no_likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.appusers')),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.appusers')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.posts')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('comment_date', models.DateTimeField()),
                ('no_likes', models.IntegerField(default=0)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.appusers')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.posts')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.appusers')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_hub.postcomments')),
            ],
        ),
    ]
