# Generated by Django 3.1 on 2020-08-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('token', models.CharField(max_length=400, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_endpoints.appusers')),
            ],
        ),
    ]
