# Generated by Django 3.1 on 2020-08-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0003_auto_20200811_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='involved_in_friendships', to='api_endpoints.appusers')),
                ('friendship_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_friendships', to='api_endpoints.appusers')),
            ],
        ),
    ]
