# Generated by Django 3.1 on 2020-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0004_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
