# Generated by Django 3.1 on 2020-09-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0006_auto_20200901_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFriendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to='api_endpoints.appusers')),
                ('requested_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_friendships', to='api_endpoints.appusers')),
            ],
        ),
    ]
