# Generated by Django 3.1 on 2020-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoints', '0007_pendingfriendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingfriendship',
            name='validation_token',
            field=models.CharField(default='', max_length=6),
        ),
    ]
